--- # delius-stage all.yml
region: eu-west-2
project_name: delius
environment_name: delius-stage
simple_environment_name: stage
ndelius_version: "4.6.13"
catalog: PCAT
data_classification: official-data
delegated_account_id: "205048117103"
required_patches:
    p18371441:
      filename: p18371441_112040_Linux-x86-64.zip
      description: ORA-19755 from RMAN recover of file with missing BCT file during duplicate
      grid_patch: false
      database_patch: true
