--- # delius-stage all.yml
region: eu-west-2
project_name: delius
environment_name: delius-stage
simple_environment_name: stage
ndelius_version: "4.4.14"
catalog: PCAT
data_classification: official-data
