--- # delius-training all.yml
region: eu-west-2
project_name: delius
environment_name: delius-training
simple_environment_name: training
ndelius_version: "4.1.7.3"
catalog: DCAT
data_classification: unclassified-data