--- # delius_primarydb.yml

database_global_database: DMTNDA
database_taf_service: DMTNDA_TAF
database_primary_unique: DMTNDA
database_primary_sid: DMTNDA
cfo_database_directory: "/u01/app/oracle/admin/{{ database_global_database }}/cfo/shared_files/National/cfo"
required_patches:
    p27659043:
      filename: p27659043_11204180417_Linux-x86-64.zip
      description: MES Bundle Patch for April 2018 PSU
      postinstall_sql: postinstall.sql
      grid_patch: false
      database_patch: true