--- # delius-core-dev all.yml
region: eu-west-2
project_name: delius-core
environment_name: delius-core-dev
simple_environment_name: dev
ndelius_version: "4.4.12"
catalog: DCAT
data_classification: unclassified-data
required_patches:
    p27659043:
      filename: p27659043_11204180417_Linux-x86-64.zip
      description: MES Bundle Patch for April 2018 PSU
      postinstall_sql: postinstall.sql
      grid_patch: false
      database_patch: true