--- # delius_standbydb1.yml

database_standby_unique: PRENDAS1
database_standby_sid: PRENDAS1
database_primary_unique: PRENDA
database_parameters:
   control_management_pack_access: DIAGNOSTIC+TUNING
   adg_account_info_tracking: LOCAL
active_data_guard: true