--- # mis_primarydb.yml

database_global_database: PREMIS
database_taf_service: PREMIS_TAF
database_primary_unique: PREMIS
database_primary_sid: PREMIS
database_parameters:
   control_management_pack_access: DIAGNOSTIC
   sga_max_size: 175G
   sga_target: 175G
   pga_aggregate_target: 35G
   pga_aggregate_limit: 70G
rman_retention_policy: RECOVERY WINDOW OF 31 DAYS
rman_level_0_backup_duration_target: "15:00"
rman_uncompressed_backup: Y
required_patches:
    p32044533:
      patch_files:
         - target_version: "19.9"
           filename: p32044533_199000DBRU_Linux-x86-64.zip
      description: ORA-600 [OPIFCH2:ROWSETSEARLYRET] LOGGED IN DATABASE ALERT LOG
      grid_patch: false
      database_patch: true
      datapatch_required: false
      replaces_patch: "30616738"
delius_users:
  bbuchan_dba:
  rsingh_dba:
  dreid_dba:
  sgandalwar_dba:
  kmoss_dba:
oracle_software:
  version: 19.16
  superset_patch: p34130714_190000_Linux-x86-64.zip
  ojvm_patch: p34086870_190000_Linux-x86-64.zip
  opatch:
    version: 12.2.0.1.32
    filename: p6880880_190000_Linux-x86-64.12.2.0.1.32.zip
fsfo_mode: enabled
awr_retention_days: 40