--- # delius-po-test1 all.yml
region: eu-west-2
project_name: delius
environment_name: delius-po-test1
simple_environment_name: po-test1
ndelius_version: "4.2.9"
catalog: DCAT
data_classification: unclassified-data