--- # delius-mis-test all.yml
region: eu-west-2
project_name: delius
environment_name: delius-mis-dev
simple_environment_name: mis-dev
ndelius_version: "4.4.8.1"
catalog: DCAT
data_classification: unclassified-data